[project]
name = "bm-lrs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "polars>=1.38.0",
    "pyarrow>=23.0.0",
    "ruff>=0.15.0",
]
